name: Deploy to gsmsv

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /home/ubuntu/2026Gsm-Server
          git fetch origin
          git checkout main
          git pull origin main
          ./gradlew build -x test
          sudo systemctl restart gsm-server
          sudo systemctl status gsm-server --no-pager
